name: Build Windows App

on:
  push:
    tags:
      - 'v*' # 当推送版本标签时触发
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true
        default: '1.0.7'

# 添加权限设置
permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Update version in package.json
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            # 从标签名称中提取版本号（去除 'v' 前缀）
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          # 更新 package.json 中的版本号
          node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json')); pkg.version = '${VERSION}'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');"
          echo "当前版本: ${VERSION}"

      # 构建Windows应用
      - name: Build Windows App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 构建Windows应用
          yarn build:win
        
      # 检查构建产物
      - name: List build artifacts
        shell: bash
        run: |
          echo "检查dist目录内容："
          ls -la dist/
          echo "检查EXE文件："
          find dist -name "*.exe" | sort
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/latest*.yml
            dist/*.blockmap
          if-no-files-found: warn

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/latest*.yml
            dist/*.blockmap
          draft: true
          name: "Cherry Studio ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.version) || github.ref_name }}"
          body: |
            # Cherry Studio ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.version) || github.ref_name }} 发布
            
            ## Windows下载
            - [Cherry Studio-setup.exe] - Windows安装版
            - [Cherry Studio-portable.exe] - Windows便携版
            
            ## 更新内容
            - 修复公式渲染问题
            - 优化构建流程
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
